#!/usr/bin/env python3
"""Generate art/partnerride-overview.svg — the plain-language version of the diagram.

This is the picture a new reader meets at the top of the README, so it answers
one question only: what does the extension do? Three beats — GPS position,
Bluetooth to the other bike, the distance on the ride screen. No protocol, no
legend, no dead reckoning; the only number is the one on the field. The
walkthrough is where the mechanics belong.

art/partnerride-workflow.svg is the detailed companion; shared palette, glyphs
and timing helpers live in art/svgkit.py.
"""

from pathlib import Path

from svgkit import (A_COL, B_COL, BG, BLE, FAINT, MUTED, PANEL_EDGE, TEXT, YELLOW,
                    Timeline, bike, bt_rune, satellite, txt)

W, H = 900, 400
SCORE = 20.0                # three beats of ~6 s
PLAY_RATE = 1.0
_T = Timeline(SCORE, PLAY_RATE)
fade, motion, draw_on = _T.fade, _T.motion, _T.draw_on

# ---------------------------------------------------------------- geometry
LANE_Y, LANE_H = 140, 78
HUB_Y = 196
YOU, PARTNER = 210, 650
SAT = (430, 40)
CAPTION_Y = 262

# ---------------------------------------------------------------- timeline
B1, B2, B3 = (0.8, 6.6), (7.0, 13.0), (13.4, 19.4)
HOLD = 19.0

out = []


def add(s):
    out.append(s)


def beat(t0, t1, line):
    """The one line of narration under the riders."""
    return f'<g>{fade(t0, t1)}{txt(W/2, CAPTION_Y, line, 15, TEXT, anchor="middle")}</g>'


# ================================================================= document
add('<?xml version="1.0" encoding="UTF-8"?>')
add('<!-- PartnerRide, the short version. Generated by art/gen-overview-svg.py - edit that. -->')
add(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" '
    f'role="img" aria-labelledby="ttl dsc">')
add('<title id="ttl">What PartnerRide does</title>')
add('<desc id="dsc">Two riders, each with a Karoo. Both get their position from GPS and send it '
    'straight to the other bike over Bluetooth — no internet, no phone — and the distance between '
    'the two of you appears on your ride screen.</desc>')

add('<defs>')
add(f'<marker id="aw" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" '
    f'orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{TEXT}"/></marker>')
add(f'<marker id="ap" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" '
    f'orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{BLE}"/></marker>')
add('<linearGradient id="lane" x1="0" y1="0" x2="0" y2="1">'
    '<stop offset="0" stop-color="#202836"/><stop offset="1" stop-color="#151a22"/></linearGradient>')
add('</defs>')

add(f'<rect width="{W}" height="{H}" fill="{BG}"/>')

# ---------------------------------------------------------------- the stage
add(f'<rect x="30" y="{LANE_Y}" width="{W-60}" height="{LANE_H}" rx="10" fill="url(#lane)" '
    f'stroke="{PANEL_EDGE}"/>')
add(f'<line x1="42" y1="{LANE_Y+LANE_H/2}" x2="{W-42}" y2="{LANE_Y+LANE_H/2}" stroke="#3a4453" '
    f'stroke-width="3" stroke-dasharray="26 22" opacity="0.5">'
    f'<animate attributeName="stroke-dashoffset" values="0;-48" dur="1.1s" repeatCount="indefinite"/>'
    f'</line>')
add(satellite(SAT[0], SAT[1]))
add(bike(YOU, HUB_Y, A_COL))
add(bike(PARTNER, HUB_Y, B_COL))
add(txt(YOU, HUB_Y + 42, "you", 14, A_COL, anchor="middle", weight="700"))
add(txt(PARTNER, HUB_Y + 42, "your partner", 14, B_COL, anchor="middle", weight="700"))

# ================================================================= 1 · GPS
for bx, col, t0 in ((YOU, A_COL, 1.0), (PARTNER, B_COL, 2.4)):
    x0 = SAT[0] + (-20 if bx < SAT[0] else 20)
    y0 = SAT[1] + 26
    x1, y1 = bx + (10 if bx < SAT[0] else -10), LANE_Y - 14
    add(f'<g>{fade(t0, B1[1])}<line x1="{x0}" y1="{y0}" x2="{x1}" y2="{y1}" stroke="{col}" '
        f'stroke-width="1.8" stroke-dasharray="4 6" opacity="0.6"/></g>')
    add(f'<g>{fade(t0 + 0.4, t0 + 2.2, 0.15, 0.15)}<circle r="6" fill="{col}">'
        f'{motion(f"M{x0},{y0} L{x1},{y1}", t0 + 0.4, t0 + 1.8)}</circle></g>')
add(beat(*B1, "Each Karoo gets its own position from GPS"))

# ================================================================= 2 · Bluetooth
ARC_TOP = LANE_Y - 76      # control point; the curve itself peaks at LANE_Y-46
arc = f"M{YOU+40},{LANE_Y-16} Q{(YOU+PARTNER)/2},{ARC_TOP} {PARTNER-40},{LANE_Y-16}"
add(f'<g>{fade(B2[0], B2[1])}'
    f'<path d="{arc}" fill="none" stroke="{BLE}" stroke-width="2" stroke-dasharray="4 6" '
    f'opacity="0.75" marker-start="url(#ap)" marker-end="url(#ap)"/>'
    f'</g>')
add(f'<g>{fade(B2[0]+0.2, B2[1])}'
    f'<circle cx="{(YOU+PARTNER)/2}" cy="{LANE_Y-46}" r="23" fill="#171531" stroke="{BLE}"/>'
    f'{bt_rune((YOU+PARTNER)/2, LANE_Y-46, 0.8, BLE, 3.2)}</g>')
for t0, rev in ((7.8, False), (9.2, True), (10.6, False)):
    path = arc if not rev else (f"M{PARTNER-40},{LANE_Y-16} "
                                f"Q{(YOU+PARTNER)/2},{ARC_TOP} {YOU+40},{LANE_Y-16}")
    add(f'<g>{fade(t0, t0 + 2.2, 0.2, 0.3)}<circle r="6" fill="{BLE}">'
        f'{motion(path, t0, t0 + 2.0)}</circle></g>')
add(beat(*B2, "…and sends it straight to the other bike over Bluetooth"))

# ================================================================= 3 · the gap
LINE_Y = 112
add(f'<g>{fade(13.8, HOLD)}'
    f'<line x1="{YOU}" y1="{LINE_Y-6}" x2="{YOU}" y2="{LANE_Y-4}" stroke="{TEXT}" stroke-width="1.4" opacity="0.55"/>'
    f'<line x1="{PARTNER}" y1="{LINE_Y-6}" x2="{PARTNER}" y2="{LANE_Y-4}" stroke="{TEXT}" stroke-width="1.4" opacity="0.55"/>'
    f'<line x1="{YOU}" y1="{LINE_Y}" x2="{PARTNER}" y2="{LINE_Y}" stroke="{TEXT}" stroke-width="2" '
    f'marker-start="url(#aw)" marker-end="url(#aw)" stroke-dasharray="{PARTNER-YOU}" '
    f'stroke-dashoffset="0">{draw_on(PARTNER-YOU, 13.8, 15.0)}</line></g>')
add(f'<g>{fade(15.0, HOLD)}'
    f'{txt((YOU+PARTNER)/2, LINE_Y-10, "28 m", 14, TEXT, anchor="middle", weight="600")}</g>')
add(beat(*B3, "…and the distance between you shows on your ride screen"))

# the ride-screen field: an empty slot from the start, filled in on the last beat.
# The filled version is drawn last and is opaque, so a renderer without SMIL shows it.
FX, FY, FW, FH = W/2 - 96, 292, 192, 68
add(f'<rect x="{FX}" y="{FY}" width="{FW}" height="{FH}" rx="10" fill="#161b23" stroke="{PANEL_EDGE}"/>')
add(txt(W/2, FY + 26, "PARTNER GAP", 10, FAINT, anchor="middle", mono=True))
add(txt(W/2, FY + 52, "—", 22, FAINT, anchor="middle", weight="700"))
add(txt(W/2, FY + 86, "on your Karoo ride screen", 11.5, MUTED, anchor="middle"))
add(f'<g>{fade(15.6, HOLD)}'
    f'<rect x="{FX}" y="{FY}" width="{FW}" height="{FH}" rx="10" fill="{YELLOW}"/>'
    f'{txt(W/2, FY + 50, "28 m ▲", 34, "#101418", anchor="middle", weight="700")}'
    f'</g>')

add('</svg>')

dest = Path(__file__).resolve().parent / "partnerride-overview.svg"
dest.write_text("\n".join(out), encoding="utf-8")
print(f"wrote {dest} ({dest.stat().st_size} bytes)")
